appeals_novoross/api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets

from . import views
# from .views import APIapeals

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

app_name = 'api'
urlpatterns = [
      path('', include(router.urls)),
      path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
      path('form/<str:uid>', views.formpage, name='formpage'),
      path('form/<str:uid>/insert', views.form_insert, name='form_insert'),
      
      path('apeals/', views.APIapeals),
]

appeals_novoross/appeals_novoross/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.index, name='landing'),
    path('apeals/<str:apeals_uid>', views.apeals_view, name='apeals_view'),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('form/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    
    
]

appeals_novoross/dashboard/urls.py
from django.urls import path, include

from . import views

app_name = 'dashboard'
urlpatterns = [

    path('', views.index, name='dashboard'),
    path('apeals', views.apeals, name='apeals'),
    path('apeals/details/<int:apeals_id>', views.apeals_details, name='apeals_details'),
    
]

appeals_novoross/dashboard/models.py
from django.contrib.postgres.fields import ArrayField
from django.utils.crypto import get_random_string
from django.db import models
from model_utils import Choices
from phone_field import PhoneField
from datetime import datetime
from api.models import ExternalForm

class Subject(models.Model):
      first_name = models.CharField(null=True, blank=True, max_length=64, verbose_name="Имя")
      midle_name = models.CharField(null=True, blank=True, max_length=64, verbose_name="Отчество")
      last_name = models.CharField(null=True, blank=True, max_length=64, verbose_name="Фамилия")
      gender = models.CharField(null=True, blank=True, max_length=64, verbose_name="Пол")
      phone = PhoneField(null=True, blank=True, verbose_name="Телефон", unique=True)
      email = models.EmailField(null=True, blank=True, max_length=128, verbose_name="Email")
      addres = models.CharField(null=True, blank=True, max_length=256, verbose_name="Адрес")
      addres_arr = models.TextField(null=True, blank=True)

      delo_id = models.IntegerField(verbose_name="Дело ID пользователя", default=0)

      def __str__(self):
            return f"{self.first_name} {self.last_name}"



class Apeals(models.Model):
      STATUSES = Choices(
            (0, 'new', 'Новое'),
            (1, 'woked', 'В работе'),
            (2, 'redirect', 'Перенаправлено'),
            (3, 'response', 'Требуется ответ гражданина'),
            (10, 'closed', 'Завершено'),
      )
      FORMAT = Choices(
            (0, 'forms', 'Обращения с формы'),
            (1, 'email', 'Email обращения'),
            (2, 'phone', 'Входящий звонок')
      )
      subject = models.ForeignKey(
            Subject,
            on_delete=models.CASCADE,
            related_name="subject",
            related_query_name="subject",
            null=True, blank=True

      )
      form = models.ForeignKey(
            ExternalForm,
            on_delete=models.CASCADE,
            related_name="form",
            related_query_name="form",
            null=True, blank=True
      )
      content = models.TextField(verbose_name="Текст обращения", default="Без сообщения")
      file = models.FileField(verbose_name="Файл", null=True, blank=True)
      destination = models.CharField(max_length=128, verbose_name="Адресат обращения", null=True, blank=True)
      topic = models.CharField(max_length=128, verbose_name="Тема обращения", null=True, blank=True)
      status = models.IntegerField(choices=STATUSES, default=0)
      format = models.IntegerField(choices=FORMAT, default=0)
      created = models.DateTimeField(default=datetime.now())
      updated = models.DateTimeField(auto_now=True)
      reminder = models.DateTimeField(null=True, blank=True)

      uid = models.CharField(max_length=16, default=get_random_string(length=8))

      delo_id = models.IntegerField(verbose_name="Дело ID обращения", default=0)


class ApealsComments(models.Model):
      TYPES = Choices(
            (0, 'system', 'Системное сообщение'),
            (1, 'message', 'Сообщение'),
      )
      apeals = models.ForeignKey(
            Apeals,
            on_delete=models.CASCADE,
            related_name="apeal",
            related_query_name="apeal"
      )
      message = models.TextField(null=True)
      type = models.IntegerField(choices=TYPES, default=1)
      created = models.DateTimeField(default=datetime.now())

appeals_novoross/dashboard/forms.py
from django import forms
from django.forms import CharField, ModelForm
import django_filters

from .models import Apeals, ApealsComments

class ApealsDetailsForm(forms.ModelForm):

      class Meta:
            model = Apeals
            fields = ('status', 'topic', 'destination')

            labels = {
                'status': 'Статус',
            }

class ApealsCommentsForm(forms.ModelForm):

      class Meta:
            model = ApealsComments
            fields = ('message', )

            widgets = {
                  'message': forms.Textarea(attrs={'placeholder': 'Комментарий', 'data-toggle': 'autosize', 'rows': '3', 'maxlength': '250', 'oninput': '$("#message_counter").text($(this).val().length+"/250")'}),
            }
            labels = {
                'message': 'Сообщение пользователю',
            }

# Фильтр обращений
class ApealsFilter(django_filters.FilterSet):
    class Meta:
        model = Apeals
        fields = ['status', 'format', 'created']

appeals_novoross/dashboard/views.py
from django.shortcuts import render

from datetime import datetime

import requests

from appeals_novoross.views import direction_identifier
from .models import Apeals, Subject, ApealsComments
from .forms import ApealsCommentsForm, ApealsDetailsForm, ApealsFilter

from django_mailbox.models import Message


# * Методы
# Для автоматического сбора писем с электронных ящиков необходимо настроить CRON задачу на выполение python manage.py getmail

def index(request):

      return render(request, "dashboard.html", context={"data": 'data'})

def apeals(request):
      #* Получение и обработка входящих емейлов
      messages = Message.objects.filter(read=None)

      for message in messages:

            message_title = str(message)
            print(message_title)
            recognized_data = direction_identifier(message.text)

            author, created = Subject.objects.get_or_create(
                  email = message.from_address[0]
            )
            
            message.read = datetime.now()
            message.save()

            # Сохранение емейла как обращения
            Apeals.objects.create(subject=author, content=message_title+" - "+message.text, destination=recognized_data[1][1], topic=recognized_data[0][1], format = 1)

      apeals_filter = ApealsFilter(request.GET, queryset=Apeals.objects.all())
      # Данные для вывода
      data = {
            'apeals': apeals_filter
      }


      return render(request, "apeals_list.html", context={"data": data})

def apeals_details(request, apeals_id):

      cApeal = Apeals.objects.get(id=apeals_id)
      if "add_comment" in request.POST:

                comment_form = ApealsCommentsForm(request.POST)

                if comment_form.is_valid():

                    add_comment(comment_form, cApeal, 1)

      if "update_apeals" in request.POST:
            
            apeals_detail = ApealsDetailsForm(request.POST, instance=cApeal) 

            if apeals_detail.is_valid():
                  apeals_detail.save()
                  add_comment(ApealsCommentsForm(), cApeal, 0, 'Обращение обновлено')

      apeals_detail_form = ApealsDetailsForm(instance=cApeal)
      comment_form = ApealsCommentsForm()

      data = {
            'apeals_data': cApeal,
            'apeals_form': apeals_detail_form,
            'comments': ApealsComments.objects.filter(apeals=apeals_id),
            'comment_form': comment_form
      }
      return render(request, "apeals_details.html", context={"data": data})


def add_comment(form, model_object, type, message=False):
    comment = form.save(commit=False)
    comment.apeals = model_object
    comment.type = type
    if message != False:
        comment.message = message
    comment.save()

    send_sms(type)

# Отправка тестовых СМС через SMS.RU
def send_sms(type, phone = 79180325232):
      if type == 0:
            url = f"https://sms.ru/sms/send?api_id=A49CFEEC-E148-B593-53B7-44FB89DD73B1&to={phone},&msg=Обращение+обновлено+ld.moshikov.co/apeals/E24H0V3Cu&json=1"
      else: 
            url = f"https://sms.ru/sms/send?api_id=A49CFEEC-E148-B593-53B7-44FB89DD73B1&to={phone},&msg=Вы+получили+новое+сообщение+к+своему+обращению+ld.moshikov.co/apeals/E24H0V3Cu&json=1"

      payload  = {}
      headers= {}

      response = requests.request("POST", url, headers=headers, data = payload)

appeals_novoross/dashboard/templates/apeals_details.html
{% extends "base.html" %}
{% load static %}
{% block main %}
{% load widget_tweaks %}
<div class="row justify-content-center py-4">


    </div>
    <div class="row">
        <div class="col-12 col-md-4">

            <div class="card text-center">
                <div class="card-header">
                    <h5 class="mb-0">Карточка обращения</h5>
                </div>
                <div class="card-body pt-0">
                <form method="post" id="apeals_form" class="mt-4">
                        {% csrf_token %}
                        {% for hidden in data.apeals_form.hidden_fields %}
                        {{ hidden }}
                        {% endfor %}
                    <table class="table">
                        <tbody>
                            <tr>
                                <td scope="row">Дата создания</td>
                                <td>{{data.apeals_data.created}}</td>
                            </tr>
                            <tr>
                                <td scope="row">Срок исполнения</td>
                                <td>{{data.apeals_data.reminder}}</td>
                            </tr>
                            <tr>
                                <td scope="row">Последнее обновление</td>
                                <td>{{data.apeals_data.updated}}</td>
                            </tr>
                            {% for field in data.apeals_form.visible_fields %}
                            <tr>
                                <td scope="row">{{ field.label }}</td>
                                <td>{{ field|add_class:'form-control border border-light-gray mb-4' }}</td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td scope="row">ID обращения в "Дело"</td>
                                <td>{{data.apeals_data.delo_id}}</td>
                            </tr>
                            <tr>
                                <td scope="row">ID субъекта в "Дело"</td>
                                <td>{{data.apeals_data.subject.delo_id}}</td>
                            </tr>

                        </tbody>
                    </table>

                        <button type="" class="btn btn-block btn-light" name="update_apeals">Обновить</button>
                    </form>
                    
                </div>
            </div>
        </div>
        <div class="col-12 col-md-8">
            <div class="card bg-white border-light p-4 mb-4">
                <div class="d-flex justify-content-between align-items-center mb-2">
                    <span class="font-small">
                        <a href="#">
                            <span class="font-weight-bold">#{{data.apeals_data.subject.id}}
                                {% if data.apeals_data.subject.first_name %} {{data.apeals_data.subject.first_name}}
                                {{data.apeals_data.subject.last_name}} {% else %} Имя не указано{% endif %}</span>
                        </a>
                        <span class="ml-2">{{data.apeals_data.created}}</span>
                    </span>

                </div>
                <p class="m-0">{{data.apeals_data.content}}</p>
            </div>
            
            
            {% for comment in data.comments %}

                {% if comment.type == 0 %}
                    {% include 'includes/system_comment.html' with comment=comment %}
                {% else %}
                    {% include 'includes/comment.html' with comment=comment %}
                {% endif %}

            {% endfor %}

            <form method="post" id="comment_form" class="mt-4">
                {% csrf_token %}
                {% for hidden in data.comment_form.hidden_fields %}
                {{ hidden }}
                {% endfor %}

                {% for field in data.comment_form.visible_fields %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}" class="h6 text-dark">{{ field.label }}</label>
                    {{ field|add_class:'form-control border border-light-gray mb-4' }}
                    {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                </div>
                {% endfor %}
                <div class="d-flex justify-content-between align-items-center mt-3">
                    <div class="file-field">
                        <div class="d-flex justify-content-left">
                            <div class="d-flex">
                                <span class="icon icon-md h6"><span class="fas fa-paperclip mr-3"></span></span>
                                <input type="file">
                                <div class="d-md-block text-left d-none d-sm-block">
                                    <div class="font-weight-normal text-dark mb-1">Прикрепление файла</div>
                                    <div class="text-gray small pr-1 pr-lg-6">Поддерживаемый формат: jpg, jpeg, png,
                                        doc, pdf, gif, zip, rare, tar, txt, xls, docx, xlsx, odt
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-secondary" name="add_comment"><span
                            class="fas fa-paper-plane mr-2"></span>Отправить</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main %}

appeals_novoross/dashboard/templates/apeals_list.html
{% extends "base.html" %}
{% load static %}
{% block main %}
{% load widget_tweaks %}
<div class="d-flex justify-content-between align-items-center pb-2 pt-4 pb-md-4"><div><a href="./single-message.html" class="btn btn-secondary disabled mb-3 mb-md-0"><span class="fas fa-plus mr-2"></span><span>Добавить</span></a></div>
<div class="d-block d-sm-flex">
<form method="GET" class="d-flex align-items-center">
      {% render_field data.apeals.form.status class="select-2 select-filter custom-select select2-hidden-accessible mx-2" %}
      {% render_field data.apeals.form.format class="select-2 select-filter custom-select select2-hidden-accessible mx-2" %}
      <button class="btn btn-primary"><span class="fas fa-filter"></span></button>
</form>
</div>
</div>
<div class="border bg-white border-light shadow-sm py-1 rounded">
      {% for apeals in data.apeals.qs %}
      <div class="card hover-state border-bottom rounded-0 py-3">
            <div class="card-body d-flex align-items-center flex-wrap flex-lg-nowrap py-0">
                  <div class="col-12 col-lg-2 pl-0">

                  {% if apeals.status == 0 %}
                        <span class="badge badge-secondary mr-2">{{ apeals.get_status_display }}</span>
                  {% elif apeals.status == 3 %}
                    <span class="badge badge-secondary mr-2">{{ apeals.get_status_display }}</span>
                  {% else %}
                        <span class="mr-2">{{ apeals.get_status_display }}</span>
                  {% endif%}


                  {% if apeals.format == 0 %}
                        <i class="fab fa-wpforms mr-2"></i> Форма <span class="badge badge-info ml-2">{{ apeals.form }}</span>
                  {% elif apeals.format == 1 %}
                        <i class="fa fa-envelope mr-2"></i> Email
                  {% elif apeals.format == 2 %}
                        <i class="fa fa-phone mr-2"></i> Телефон
                  {% endif%}


                  </div>
                  <div class="col-10 col-lg-3 pl-0">
                        <span class="h6 font-weight-normal mb-0">#{{ apeals.subject.id }} {{ apeals.subject }}</span>
                  </div>

                  <div class="col-2 col-lg-2 d-flex align-items-center justify-content-end px-0 order-lg-4">
                        <div class="text-muted small d-none d-lg-block">{{ apeals.created }}</div>
                  </div>
                  <div class="col-12 col-lg-5 d-flex align-items-center mt-3 mt-lg-0 pl-0">
                        <a href="{% url 'dashboard:apeals_details' apeals.id %}" class="font-weight-normal text-gray truncate-text">
                              <span class="font-weight-normal">{{ apeals.content }}</span>
                        </a>
                  </div>
            </div>
      </div>
      {% endfor %}

      <div class="row p-4">
            <div class="col-7 mt-1">
                  Showing 1 - 20 of 289
            </div> <!-- end col-->
            <div class="col-5">
                  <div class="btn-group float-right">
                        <a href="#" class="btn btn-light"><span class="fas fa-chevron-left"></span></a>
                        <a href="#" class="btn btn-primary"><span class="fas fa-chevron-right"></span></a>
                  </div>
            </div> <!-- end col-->
      </div>
</div>

{% endblock main %}

appeals_novoross/dashboard/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block main %}
{% load widget_tweaks %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4">
</div>
<div class="alert alert-warning">Данный дашборд носит частично иллюстрационный вариант основанный на статичных данных</div>
<div class="row justify-content-md-center">
      <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-light shadow-sm">
                  <div class="card-body">
                        <div class="text-xl-center mb-3 mb-xl-0 d-flex align-items-center">
                              <div class="icon icon-shape icon-md icon-shape-primary rounded mr-4"><span class="fas fa-chart-line px-4"></span></div>
                              <div class="">
                                    <h2 class="h5">Обращения</h2>
                                    <h3 class="mb-1">124</h3>
                              </div>
                        </div>
                  </div>
            </div>
      </div>

      <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-light shadow-sm">
                  <div class="card-body">
                        <div class="text-xl-center mb-3 mb-xl-0 d-flex align-items-center">
                              <div class="icon icon-shape icon-md icon-shape-tertiary rounded mr-4"><span class="fas fa-users px-4"></span></div>
                              <div class="">
                                    <h2 class="h5">Пользователи</h2>
                                    <h3 class="mb-1">1 245</h3>
                              </div>
                        </div>
                  </div>
            </div>
      </div>

      <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-light shadow-sm">
                  <div class="card-body">
                        <div class="row d-block d-xl-flex align-items-center">
                              <div
                                    class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                                    <div class="ct-chart-traffic-share ct-golden-section ct-series-a"></div>
                              </div>
                              <div class="col-12 col-xl-7 px-xl-0">
                                    <h2 class="h5">Обращения</h2>
                                    <h6 class="font-weight-normal text-gray"><span
                                                class="icon w-20 icon-xs icon-secondary mr-1"><span
                                                      class="fa fa-envelope"></span></span> Email <a href="#"
                                                class="h6">70%</a></h6>
                                    <h6 class="font-weight-normal text-gray"><span
                                                class="icon w-20 icon-xs icon-primary mr-1"><span
                                                      class="fab fa-wpforms"></span></span> Формы <a href="#"
                                                class="h6">30%</a></h6>
                              </div>
                        </div>
                  </div>
            </div>
      </div>
      <div class="col-12 col-xl-8 mb-4">
            <div class="card border-light shadow-sm">
                  <div class="card-body d-flex flex-row align-items-center flex-0 border-bottom">
                        <div class="d-block">
                              <div class="h6 font-weight-normal text-gray mb-2">Обращения по дням</div>
                              <h2 class="h3">452</h2>
                              <div class="small mt-2">
                                    <span class="fas fa-angle-up text-success"></span>
                                    <span class="text-success font-weight-bold">18.2%</span>
                              </div>
                        </div>
                        <div class="d-block ml-auto">
                              <div class="d-flex align-items-center text-right mb-2">
                                    <span class="shape-xs rounded-circle bg-primary mr-2"></span>
                                    <span class="font-weight-normal small">Формы</span>
                              </div>
                              <div class="d-flex align-items-center text-right">
                                    <span class="shape-xs rounded-circle bg-secondary mr-2"></span>
                                    <span class="font-weight-normal small">Email</span>
                              </div>
                        </div>
                  </div>
                  <div class="card-body p-2">
                        <div class="ct-chart-ranking ct-golden-section ct-series-a"></div>
                  </div>
            </div>
      </div>
</div>
{% endblock main %}