appeals_novoross/api/urls.py
from django.urls import path, include
from rest_framework import routers, serializers, viewsets

from . import views
# from .views import APIapeals

router = routers.DefaultRouter()
# router.register(r'users', UserViewSet)

app_name = 'api'
urlpatterns = [
      path('', include(router.urls)),
      path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
      path('form/<str:uid>', views.formpage, name='formpage'),
      path('form/<str:uid>/insert', views.form_insert, name='form_insert'),
      
      path('apeals/', views.APIapeals),
]

appeals_novoross/appeals_novoross/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url
from django.conf import settings

from . import views

urlpatterns = [
    path('', views.index, name='landing'),
    path('apeals/<str:apeals_uid>', views.apeals_view, name='apeals_view'),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('form/', include('dashboard.urls')),
    path('api/', include('api.urls')),
    
    
]

appeals_novoross/api/models.py
from django.db import models
from django.utils.crypto import get_random_string

# Create your models here.
class ExternalForm(models.Model):
      title = models.CharField(max_length=64, verbose_name="Источник")
      uid = models.CharField(max_length=32, default=get_random_string(length=32))
      
      def __str__(self):
        return self.title
      

appeals_novoross/api/forms.py
from django import forms
from django.forms import CharField, ModelForm

import json 

from .models import ExternalForm
from dashboard.models import Apeals, Subject

class ExternalApealsForm(forms.ModelForm):

      # form = forms.IntegerField()
      author = forms.CharField(label='Ваше имя')
      phone = forms.CharField(label='Телефон')
      email = forms.EmailField(label='Электронная почта')
      addres = forms.CharField(label='Ваш адрес')
      dadata_fio = forms.CharField(widget=forms.HiddenInput(), required=False)
      dadata_addres = forms.CharField(widget=forms.HiddenInput(), required=False)
      user_id = forms.CharField(widget=forms.HiddenInput(), required=False)

      class Meta:
            model = Apeals
            fields = ('content', 'file', 'form')

            widgets = {
                  'content': forms.Textarea(attrs={'data-toggle': 'autosize', 'rows': '3'}),
                  'subject': forms.NumberInput()
            }
            labels = {
                'content': 'Обращение',
                'file': 'Добавить файл (PDF, Фото/Видео)',

            }


      
      def __init__(self, uid, *args, **kwargs):
            super(ExternalApealsForm, self).__init__(*args, **kwargs)
            # print(uid)
            # self.fields['form'].initial = ExternalForm.objects.get(uid=uid)
            # print(self.fields['form'])

      def save(self, commit=True):
            author_info = json.loads(self.cleaned_data['dadata_fio'])
            author_addres = json.loads(self.cleaned_data['dadata_addres'])
            
            author, created = Subject.objects.get_or_create(
                  first_name = author_info['data']['name'],
                  phone = self.cleaned_data['phone'],
                  
            )
            
            if created:
                  author.midle_name = json.dumps(author_info['data']['patronymic']),
                  author.last_name = json.dumps(author_info['data']['surname']),
                  author.gender = json.dumps(author_info['data']['gender']),
                  author.email = self.cleaned_data['email'],
                  author.addres = json.dumps(author_addres['value'])
                  author.save()

            self.cleaned_data['subject'] = author.id
            


            return super(ExternalApealsForm, self).save(commit)

appeals_novoross/api/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.clickjacking import xframe_options_exempt

from rest_framework.response import Response
from rest_framework.views import APIView

from django.forms import inlineformset_factory


from .models import ExternalForm
from dashboard.models import Subject, Apeals

from .forms import ExternalApealsForm


@csrf_exempt
@xframe_options_exempt
def formpage(request, uid):
      print("Старница формы")
      Form = get_object_or_404(ExternalForm, uid=uid)

      if request.method == "POST":
            print('Форма отправлена')
            apeals_form = ExternalApealsForm(uid, request.POST)
            if apeals_form.is_valid():
                  print('Форма ВАЛИДНА')
                  print(apeals_form)
                  apeals = apeals_form.save(commit=False)
                  apeals.form = ExternalForm.objects.get(uid=uid)
                  # print(apeals.subject)
                  apeals.save()
      else:
            print('Пустая форма')
            apeals_form = ExternalApealsForm(uid)
            
            print(apeals_form['form'])

      # print(apeals_form)

      # BookFormSet = inlineformset_factory(Subject, Apeals, fields=('first_name', 'title',))

      return render(request, "form_frame.html", context={"form": apeals_form})

def form_insert(request, uid):
      Form = get_object_or_404(ExternalForm, uid=uid)
      code = f'<iframe width="100%" height="950px" src="http://127.0.0.1:8000/api/form/{uid}"></iframe>'
      title = Form.title
      return render(request, "form_insert_code.html", context={"code": code, "title": title})


def APIapeals(APIView):

      def get(self, request):
            apeals = Apeals.objects.all()
            
            return Response({"apeals": apeals})

appeals_novoross/api/templates/form_frame.html
{% load widget_tweaks %}
{% load static %}
<style>body { background: transparent !important}</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/suggestions-jquery@20.3.0/dist/css/suggestions.min.css" rel="stylesheet" />
<link type="text/css" href="{% static 'css/rocket.css' %}" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/suggestions-jquery@20.3.0/dist/js/jquery.suggestions.min.js"></script>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-8">
        <div class="card shadow-sm text-dark">
          <div class="card-header px-4 d-flex align-items-center justify-content-center">
            {% comment %} <img height="60px" src="{% static 'img/Coat_of_Novorossiysk.png' %}" class="mr-4"> {% endcomment %}
            <div>
            <p class="h6 text-dark mb-0">Обращение жителя Новороссийска к администрации города</p>
            {% comment %} <p><small>Отправьте нам форму с обращением, и мы обязательно ее рассмотрим.Мы стремимся улучшить наш город.</small><p> {% endcomment %}
            </div>
          </div>
          <div class="card-body">
            <form method="post" class="d-flex flex-column">
              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}

              {% for field in form.visible_fields %}
              {% if field.name != 'form' %}
                <div class="form-group {% if field.name == 'author' %}order-1{% elif field.name == 'addres' %}order-2{% elif field.name == 'phone' %}order-3{% elif field.name == 'email' %}order-4{% elif field.name == 'content' %}order-5{% elif field.name == 'file' %}order-6{% endif %} "> 
                  <label for="{{ field.id_for_label }}" class="h6 text-dark">{{ field.label }}</label>
                  {{ field|add_class:'form-control' }}
                  {% for error in field.errors %}
                  <span class="help-block">{{ error }}</span>
                  {% endfor %}
                </div>
              {% endif %}
              {% endfor %}
              <div class="form-group order-10">
                <button type="submit" class="btn btn-primary btn-block">
                  <span class="glyphicon glyphicon-ok"></span> Отправить
                </button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

<script>
  $("#id_addres").suggestions({
    token: "07969428f1a6bafdeee20417d4dadbe124f960e0",
    type: "ADDRESS",
    /* Вызывается, когда пользователь выбирает одну из подсказок */
    onSelect: function (suggestion) {
      $("#id_dadata_addres").val(JSON.stringify(suggestion))
      console.log(suggestion);
    }
  });
  $("#id_author").suggestions({
    token: "07969428f1a6bafdeee20417d4dadbe124f960e0",
    type: "NAME",
    /* Вызывается, когда пользователь выбирает одну из подсказок */
    onSelect: function (suggestion) {
      $("#id_dadata_fio").val(JSON.stringify(suggestion))
      console.log(suggestion);
    }
  });
</script>

appeals_novoross/api/templates/form_insert_code.html
{% load widget_tweaks %}
{% load static %}
<link type="text/css" href="{% static 'css/rocket.css' %}" rel="stylesheet">

<div class="container">
<div class="card shadow-sm text-dark">
  <div class="card-header">
    <h4 class="card-title">Код формы "{{title}}"</h4>
  </div>
  <div class="card-body">
    <pre class="mb-2" id="code_snippet">{{code}}</pre>
    <button class="btn btn-outline-primary btn-block" onclick="copyFunc()">Скопировать</button>
  </div>
</div>


<script>
function copyFunc() {
  /* Get the text field */
  var copyText = document.getElementById("code_snippet").textContent;

  document.execCommand("copy");

  alert("Код скоприрован");
}
</script>
</div>